name: Build UI

on:
  push:
    branches: [ main, 'feature/*', 'fix/*', 'chore/*' ]
    paths:
      - 'ui/**'
      - '.github/workflows/build-ui.yml'

concurrency:
  group: build-ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build.yml
    with:
      docker_context: ui
      image_name: vlm-node-ui
      docker_platforms: linux/amd64
    secrets:
      docker_registry_username: ${{ secrets.DOCKER_USERNAME }}
      docker_registry_password: ${{ secrets.DOCKER_PASSWORD }}
