name: Build UI

on:
  push:
    branches: [ 'feature/*', 'fix/*', 'chore/*' ]
    paths:
      - 'ui/**'

concurrency:
  group: build-ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      docker_context: ui
      image_name: vlm-node-ui
      docker_platforms: linux/amd64
    secrets:
      docker_registry_username: ${{ secrets.DOCKER_USERNAME }}
      docker_registry_password: ${{ secrets.DOCKER_PASSWORD }}
      argocd_host: ${{ secrets.GLOBAL_PUBLIC_ARGOCD_HOST }}
      argocd_password: ${{ secrets.GLOBAL_PUBLIC_ARGOCD_PASSWORD }}
